project:
  type: website

editor:
  render-on-save: true

#pre-render: homework/convertExercises.sh
website:
  title: "ğŸ§  EEG-2024"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course"
        contents:
            - href: course.qmd
              text: â„¹ï¸ Organisation
            - href: schedule.qmd
              text: ğŸ“† Schedule
      - section: "Projects"
        contents:
            - href: semesterproject.qmd
              text: ğŸ“‹ Descriptions
            - href: grading.qmd
              text: ğŸ› ï¸ Grading
            - href: milestones.qmd
              text: ğŸ¯ Milestones
      - section: "Exercises"
        contents:
            - href: exercises_overview.qmd
              text: â„¹ï¸ Organisation
            - href: exercises/exercises.qmd
              text: ğŸ‹ï¸â€â™‚ï¸ Exercise sheets
      - section: "Resources"
        contents:
            - href: bibliography.qmd
              text: ğŸ“š Bibliography
            - href: software.qmd
              text: ğŸ’» Software

format:
  html:
    theme: 
      - yeti
      - css/styles.scss
    css: css/styles.css
    
    toc: true
